mongodb:
  host:
  username: admin
  password: password
  port: 31000
service:
  id: mongodb
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: mongodb-service-broker
