apiVersion: v1
kind: ConfigMap
metadata:
  namespace: ${namespace}
  name: ${name}-config
data:
  mongod.conf: |
    net:
      port: 27017
    replication:
      replSetName: rs0
    storage:
      dbPath: /data/db
    security:
      authorization: disabled