apiVersion: v1
kind: Service
metadata:
  name: ${name}-discovery
  namespace: ${namespace}
spec:
  type: NodePort
  ports:
    - name: mongodb
      port: 8080
      targetPort: 27017
      nodePort: 31000
  selector:
    app: ${name}