apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: ${name}-service
  namespace: ${namespace}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: peer
      targetPort: 27017
      port: 27017
  selector:
    app: ${name}